### ISSUE TITLE
Add a needReverse field to determine if you want to rewind the animation at the end of the slide.

### ISSUE THREAD

**Issue by niu-dali** [splashbyte/action_slider#10]
Add a needReverse field to determine if you want to rewind the animation at the end of the slide.
This effect is used in the slider of the captcha, as shown in the image below, when the slide ends, the slider does not return to the origin, but stays in place.

at action_slider_widget.dart  1048 line 

`
 _slideAnimationController.reverse(from: 1.0);
`

rewrite

`
                              if (widget.needReverse) {
                                  _slideAnimationController.reverse(from: 1.0);
                              }
`

**Comment by maeddin** [comment]
This issue is solved with #16
