### ISSUE TITLE
How to keep the slider expanded on success

### ISSUE THREAD

**Issue by bgintzairspace** [splashbyte/action_slider#13]
Is it possible to keep the slider expanded on completion and not compact it to the "FAB" type result?

**Comment by maeddin** [comment]
What should the slider look like in this case? Should the indicator be stretched over the entire slider or should the slider still be operable?

**Comment by maeddin** [comment]
It is theoretically possible with the SliderMode (I think) if you create your own and disable the slider once the success state is reached.

**Comment by bgintzairspace** [comment]
@maeddin do you have any examples of using a custom SliderMode?  :)

**Comment by MohsinIkram-Auxilium** [comment]
@maeddin Here is the view I want to achieve after the sliding..
Let me knwo how can I implement this.
![image](https://github.com/splashbyte/action_slider/assets/129947950/be9a7930-37d5-483b-9f1c-d4f1a0345b17)

**Comment by berger89** [comment]
Can anyone provide an example of how to override the `SliderMode`?

**Comment by maeddin** [comment]
Sorry that it took so long, but I didn't have much free time for my open source projects.
In the [new version](https://pub.dev/packages/action_slider/versions/0.8.0-beta.0) you can now keep the slider expanded on success, failure and loading.

**Comment by maeddin** [comment]
@MohsinIkram-Auxilium Just call `controller.successExpanded()` instead of `controller.success()` in the new version :)

**Comment by ankush-westack** [comment]
Just Wrap the `ActionSlider` into the `SizedBox()` with width `double.infinite`.
It will prevent the widget collapsing.

**Comment by maeddin** [comment]
@shp-alexander-berger In the current beta version, you can switch off collapsing. This means you don't have to use such tricks.

**Comment by ankush-westack** [comment]
That's great!

> [@shp-alexander-berger](https://github.com/shp-alexander-berger) In the current beta version, you can switch off collapsing. This means you don't have to use such tricks.
