### ISSUE TITLE
Button width is not shrinking during loading,error,sucess states when used inside ListView

### ISSUE THREAD

**Issue by farookeei** [splashbyte/action_slider#14]
When the package is used inside Column,it is performing as expected.But once used in Listview,the modes change,the loading icons are shown ,but the button is not resizing according to various state changes

**Comment by IliaKomar** [comment]
> When the package is used inside Column,it is performing as expected.But once used in Listview,the modes change,the loading icons are shown ,but the button is not resizing according to various state changes

the same problem, but in my case, i use it inside of **bottomNavigationBar**

**Comment by maeddin** [comment]
Have you tried wrapping `ActionSlider` in a `Center`? Maybe `ActionSlider` gets corresponding constraints that force it to take up the entire width.

**Comment by maeddin** [comment]
I am closing the issue as it is probably solved. If the problem persists, please just open it again.
