### ISSUE TITLE
How can we add border around the slider button?

### ISSUE THREAD

**Issue by MohsinIkram-Auxilium** [splashbyte/action_slider#15]
I'm making this design. Almost everything is done. I just need to add purple border around the button. How can i do this?
Here is my code :

    Center(
                                child: ActionSlider.custom(
                                  toggleMargin: EdgeInsets.all(5),
                                  // width: 300.0,
                                  controller: _controller,
                                  toggleWidth: 50.0,
                                  height: isSmallScreen?55.0:60.0,
                                  backgroundColor: Colors.white,

                                  foregroundChild: Container(
                                      decoration: const BoxDecoration(
                                        color: AppColors.themeColor,
                                        borderRadius: BorderRadius.all(Radius.circular(18.0)),
                                      ),
                                      child: const Icon(Icons.arrow_forward, color: Colors.white)),
                                  foregroundBuilder: (context, state, child) => child!,
                                  backgroundChild: Center(
                                    child: Text('Swipe To Check In',
                                        style: TextStyle(
                                          color: AppColors.themeColor,
                                          fontWeight:
                                          FontWeight.w600,
                                          fontFamily: 'Manrope',
                                          fontSize: isSmallScreen?14.0:16,
                                        )),
                                  ),
                                  backgroundBuilder: (context, state, child) => ClipRect(
                                      child: OverflowBox(
                                          maxWidth: state.standardSize.width,
                                          maxHeight: state.toggleSize.height,
                                          minWidth: state.standardSize.width,
                                          minHeight: state.toggleSize.height,
                                          child: child!)),
                                  backgroundBorderRadius: BorderRadius.circular(18.0),

                                  action: (controller) async {
                                    controller.loading(); //starts loading animation
                                    await Future.delayed(const Duration(seconds: 3));
                                    controller.success(); //starts success animation
                                    await Future.delayed(const Duration(seconds: 1));
                                    controller.reset(); //resets the slider
                                  },
                                ),
                              ),

![image](https://github.com/splashbyte/action_slider/assets/129947950/333d4fd8-af6c-4ee0-a808-c6fba5b5d36c)

**Comment by MohsinIkram-Auxilium** [comment]
Thanks your given solution is working fine.
And again thanks for your tip. Can you please more elaborate why its not
best approach to get colors like this  AppColors.themeColor. Although I set
it as const?

**Comment by maeddin** [comment]
It is not best practice to use `const` variables for theming because you can not introduce new themes (like dark/light theme). In addition, when using `ThemeData`, you can change the colors for certain areas of the app, which is not the case with constants. So it is simply very inflexible.

**Comment by MohsinIkram-Auxilium** [comment]
Thanks for your explanation.
