### ISSUE TITLE
BackgroundColor

### ISSUE THREAD

**Issue by Mohdx** [splashbyte/action_slider#6]
Hello, good day everyone. I've faced an issue on Flutter 3.10.6 that the backgroundColor is not changing.
To fix this issue I've sent this pull request: https://github.com/splashbyte/action_slider/pull/5
By replacing `DecoratedBox` to `Container`

**Comment by maeddin** [comment]
Thanks for opening the issue and the MR :)
I will have a look at it tomorrow.
