### ISSUE TITLE
child widget collides with toggle icon

### ISSUE THREAD

**Issue by mshah21202** [splashbyte/action_slider#8]
The 'child' widget, which is the widget displayed on the background, with a large width collides with toggle icon (visually). And is centered based on the whole action slider rather than the empty part of the slider. I have created a pr #7

**Comment by maeddin** [comment]
I probably won't have time to take a closer look today. Until then, you can use your MR or manually wrap a `Padding` around `child` to solve the problem.
Thanks for creating issue and MR :)

**Comment by mshah21202** [comment]
Thank you for your time, here to help anytime!
